### PR TITLE
Add the feature to open in browser

### PR DESCRIPTION
**Pull request by TileThePlane**
To open in browser input 1 for the variable open_in_browser, for example:

toplink('wololo', 1)

This function will default to return the string url.

### CODE REVIEW

**Comment by omi10859** [comment]
Can you also please update README.md

**Comment by omi10859** [comment]
and I would also like to add you here as a maintainer of the project https://pypi.org/project/PyouPlay/

**Comment by TileThePlane** [comment]
Added to readme. Sure, feel free to add me!

**Review by omi10859 — APPROVED** [review]

**Comment by omi10859** [comment]
can you please share your username and email for PyPi @TileThePlane

**Pull request merged**
